<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Circles</title>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 
           <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
      .pgclass {
        font-weight: bold;
        color: orange;
        }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
var  = (function () {
    var json = null;
    $.ajax({
        'async': false,
        'url': "/maps/mapjson",
        'dataType': "json",
        'success': function (data) {
            json = data;
        }
    });
    return json;
})(); 
      
      function initMap() {
        // Create the map.
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: {lat: 32.857, lng: -117.2231},
        mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var infoWin = new google.maps.InfoWindow();

        // Construct the circle for each value in citymap.
        // Note: We scale the area of the circle based on the population.
        for (var data in myLoc) {

        // Create marker 
                var myLatLng = new google.maps.LatLng(myLoc[data].lat, myLoc[data].lng);

                var image = {
                    url: "http://92.222.198.138/pg_images/vertical_sprites.png",
                    size: new google.maps.Size(40, 50), // scaled size
                    origin: new google.maps.Point(0, 50*(parseInt(myLoc[data].dex) - 1)), // origin
                    anchor: new google.maps.Point(20,25) // anchor
                };
                
                var marker = new google.maps.Marker({
                    map: map,
                    position: myLatLng,
                    icon: image,
                    html: "<span class='pogo_name'>" + myLoc[data].name + "</a></span><br />" + myLoc[data].att + "<br />" + myLoc[data].lat + "," + myLoc[data].lng
                });
                    
                google.maps.event.addListener(marker, 'click', function(evt) {
                  infoWin.setContent("<span class='pgclass'>" +  myLoc[data].name + "</span><p>CO2: " + myLoc[data].s2 + "<br />pm25: " + myLoc[data].s4);
                  infoWin.open(map, this);
                })

                radiuss = 350;
                color = "green";
                var cityCircle = new google.maps.Circle({
                    strokeColor: color,
                    strokeOpacity: 1,
                    strokeWeight: 2,
                    fillColor: color,
                    fillOpacity: 0.15,
                    map: map,
                    center: myLatLng,
                    radius: radiuss
                });
        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXMKBcstoboBgrHBcho5saILTBq3PHtPQ&callback=initMap">
    </script>

</body>
</html>