<?php
abstract class signupMessage {
  const SUCCESS = 1;
  const DUPLICATED = 2;
  const NONCE_EXIST = 3;
  const NONCE_NOT_EXIST = 4;
}
if (isset($actvationResult) && !empty($actvationResult)) {
  if ($actvationResult == signupMessage::NONCE_NOT_EXIST) {
    $message = "INVALID PAGE REQUEST : NO SUCH NONCE EXIST";
    echo "<script type='text/javascript'>alert('$message');</script>";

    echo "<script> document.location.href='/'; </script>";
  }
  else {
    $message = "Account Activation Completed.";
    echo "<script type='text/javascript'>alert('$message');</script>";

    echo "<script> document.location.href='/login'; </script>";
  }
}
?>
