<!DOCTYPE html>
<html>
	<head>
		<title>ChartJS - BarGraph</title>
		<style type="text/css">
			#chart-container {
				width: 640px;
				height: auto;
			}
		</style>
	</head>
	<body>
		<div id="chart-container">
			<canvas id="mycanvas"></canvas>
		</div>

		<!-- javascript -->
		<script src="/vendors/js/vendor.bundle.base.js"></script>
	  <script src="/vendors/js/vendor.bundle.addons.js"></script>
	  <script src="/js/app.js"></script>
	</body>
</html>
