<!DOCTYPE html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="../../vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="../../vendors/iconfonts/puse-icons-feather/feather.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="../../css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
  <?php
  abstract class loginMessage {
    const SUCCESS = 1;
    const NO_SUCH_EMAIL = 2;
    const WRONG_PASSWORD = 3;
    const NONCE_EXIST = 4;
    const NONCE_NOT_EXIST = 5;
  }

  if (isset($emailResult) && !empty($emailResult)) {
    switch($emailResult) {
      case loginMessage::NO_SUCH_EMAIL:
        $message = "There is no account corresponding to input Email";
        echo "<script type='text/javascript'>alert('$message');</script>";
        break;
      case loginMessage::WRONG_PASSWORD:
        $message = "Wrong Password. Please enter again.";
        echo "<script type='text/javascript'>alert('$message');</script>";
        break;
      //case loginMessage::SUCCESS:
      //$message = "ERROR : smth wrong in checkPassword() success shouldn't be called here.";
      //echo "<script type='text/javascript'>alert('$message');</script>";
      //  break;
      case loginMessage::NONCE_EXIST:
        $message = "Please activate your account. The activation link is sent to you email.";
        echo "<script type='text/javascript'>alert('$message');</script>";
        break;
      default :
        $message = "ERROR : smth wrong in checkPassword().";
        echo "<script type='text/javascript'>alert('$message');</script>";
    }
    echo "<script> document.location.href='/login'; </script>";
  }
  abstract class newPWMessage {
      const CORRECT_PASSWORD = 1;
      const WRONG_PASSWORD = 2;
      const NO_SUCH_ACCOUNT = 3;
  }
  if (isset($pwCheckResult) && !empty($pwCheckResult)) {
    if ($pwCheckResult == newPWMessage::NO_SUCH_ACCOUNT) {
      $message = "Your account doesn't exist. Please sign-in again.";
      echo "<script type='text/javascript'>alert('$message');</script>";

      echo "<script> document.location.href='/pw_new'; </script>";
    }
  }

  ?>

  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <div class="auto-form-wrapper">
              <form method="post" action="loginHandler">
                <div class="form-group">
                  <label class="label">Email</label>
                  <div class="input-group">
                    <input type="email" class="form-control" name="email">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="label">Password</label>
                  <div class="input-group">
                    <input type="password" class="form-control" name="password">
<!--placeholder=="****"-->
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">

                  <button href="main_after" class="btn btn-primary submit-btn btn-block">Login</button>

                </div>

                <div class="form-group d-flex justify-content-between">
                  <div class="form-check form-check-flat mt-0">
  <!--
  <label class="form-check-label">
                      <input type="checkbox" class="form-check-input" checked> Keep me signed in
                    </label>
-->
                  </div>

                 <a href="forgot_pw" class="text-small forgot-password text-black align-center" >Find Password</a>

                </div>

<!--
                <div class="form-group">
                  <button class="btn btn-block g-login">
                    <img class="mr-3" src="../../images/file-icons/icon-google.svg" alt="">Log in with Google</button>
                </div>
-->

                <div class="text-block text-center my-3">
                  <span class="text-small font-weight-semibold">Not a member ?</span>
                  <a href="register" class="text-black text-small">Create new account</a>
                </div>
              </form>
            </div>
            <ul class="auth-footer">
              <li>
                <a href="#">Conditions</a>
              </li>
              <li>
                <a href="#">Help</a>
              </li>
              <li>
                <a href="#">Terms</a>
              </li>
            </ul>
            <p class="footer-text text-center">Team_A Joowon Jack James Juno Umji</p>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../vendors/js/vendor.bundle.base.js"></script>
  <script src="../../vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="../../js/off-canvas.js"></script>
  <script src="../../js/hoverable-collapse.js"></script>
  <script src="../../js/misc.js"></script>
  <script src="../../js/settings.js"></script>
  <script src="../../js/todolist.js"></script>
  <!-- endinject -->
</body>

</html>
