<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Team A</title>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 
           <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {

        height: 400px; 
        width: 900px; 
      }
      .pgclass {
        font-weight: bold;
        color: orange;
        }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
var comics = (function () {
    var json = null;
    $.ajax({
        'async': false,
        'url': "/mapjson",
        'dataType': "json",
        'success': function (data) {
            json = data;
        }
    });
    return json;
})(); 
      
      function initMap() {
        // Create the map.
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 9,
          center: {lat: 32.857, lng: -117.2231},
        mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var infoWin = new google.maps.InfoWindow();

        // Construct the circle for each value in citymap.
        // Note: We scale the area of the circle based on the population.
        for (var hero in comics) {
        // Create marker 
                var myLatLng = new google.maps.LatLng(comics[hero].latitude, comics[hero].longitude);

                
                
                var marker = new google.maps.Marker({
                    map: map,
                    position: myLatLng,
                    html: "<span class='pogo_name'>" + comics[hero].USN + "</a></span><br />" + comics[hero].latitude + "<br />" + comics[hero].longitude
                });
                    
                google.maps.event.addListener(marker, 'click', function(evt) {
                  infoWin.setContent("<span class='pgclass'>" +  comics[hero].USN + "</span><p>CO2: " + comics[hero].latitude + "<br />pm25: " + comics[hero].LO);
                  infoWin.open(map, this);
                })

        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfHa_4ZD_TIff4iowZpOutTWlpAzw_Krg&callback=initMap">
    </script>

</body>
</html>