<!DOCTYPE html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="../../vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="../../vendors/iconfonts/puse-icons-feather/feather.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="../../css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
  <?php
  abstract class newPWMessage {
      const CORRECT_PASSWORD = 1;
      const WRONG_PASSWORD = 2;
      const NO_SUCH_ACCOUNT = 3;
  }
  if (isset($pwCheckResult) && !empty($pwCheckResult)) {
    if ($pwCheckResult == newPWMessage::WRONG_PASSWORD) {
      $message = "Wrong password. Please enter your password again.";
      echo "<script type='text/javascript'>alert('$message');</script>";
    } else {
      $message = "Something went wrong in the program : " . $pwCheckResult;
      echo "<script type='text/javascript'>alert('$message');</script>";
    }
    echo "<script> document.location.href='/pw_check'; </script>";
  }
   ?>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
               <h2 class="text-center mb-4 text-white">Change Password</h2>
            <div class="auto-form-wrapper">
              <form method="post" action="pw_checkHandler" name="pwCheckForm" onsubmit="return check()">

                <div class="form-group">
                  <label class="label">Enter Your Password</label>
                  <div class="input-group">
                    <input type="password" class="form-control" name="password">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <!--a class="nav-link" href="pw_new"-->
                  <button class="btn btn-primary submit-btn btn-block">Confirm</button>
                <!--/a-->
                </div>

              </form>
            </div>
            <ul class="auth-footer">
              <li>
                <a href="#">Conditions</a>
              </li>
              <li>
                <a href="#">Help</a>
              </li>
              <li>
                <a href="#">Terms</a>
              </li>
            </ul>
            <p class="footer-text text-center">Team_A Joowon Jack James Juno Umji</p>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../vendors/js/vendor.bundle.base.js"></script>
  <script src="../../vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="../../js/off-canvas.js"></script>
  <script src="../../js/hoverable-collapse.js"></script>
  <script src="../../js/misc.js"></script>
  <script src="../../js/settings.js"></script>
  <script src="../../js/todolist.js"></script>
  <!-- endinject -->
</body>

<script>
  function check() {
    if(pwCheckForm.password.value == "") {
      alert("Password value does not exist");
      pwCheckForm.password.focus();
      return false;
    }
    else return true;
  }
</script>

</html>
