<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="../../vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="../../vendors/iconfonts/puse-icons-feather/feather.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="../../vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="../../css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
  <?php
  if (isset($_SESSION["email"])) $inputEmail = $_SESSION["email"];
  else $inputEmail = "";
  if (isset($_SESSION["firstName"])) $inputEmail = $_SESSION["firstName"];
  else $inputFirstName = "";
  if (isset($_SESSION["lastName"])) $inputEmail = $_SESSION["lastName"];
  else $inputLastName = "";
  if (isset($_SESSION["phoneNum"])) $inputEmail = $_SESSION["phoneNum"];
  else $inputPhoneNum = "";

  abstract class signupMessage {
    const SUCCESS = 1;
    const DUPLICATED = 2;
    const NONCE_EXIST = 3;
    const NONCE_NOT_EXIST = 4;
  }
  if (isset($registerResult) && !empty($registerResult)) {
    //echo "<script> document.location.href='/register'; </script>";
    switch ($registerResult) {
      case signupMessage::SUCCESS :
        // send user the response
        $message = "Sign-up is completed. Please check you email to activate you account";
        echo "<script type='text/javascript'>alert('$message');</script>";
        break;
      case signupMessage::DUPLICATED:
        $message = "The Email is already registered. Please enter other email or sign-in";
        echo "<script type='text/javascript'>alert('$message');</script>";
        break;
      default:
        $message = "ERROR : smth wrong in checkDuplicationEmail() = ".$registerResult;
        echo "<script type='text/javascript'>alert('$message');</script>";
    }
    echo "<script> document.location.href='/register'; </script>";
  }
  ?>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <h2 class="text-center mb-4">SIGN UP</h2>
            <div class="auto-form-wrapper">
              <form class="form" method="post" action="/registerHandler" name="RegisterForm" onsubmit="return check()">
                <div class="form-group d-flex justify-content-between">
                  <div class="input-group">
                    <input type="email" class="form-control" placeholder="Email" name="email" value="<?php echo $inputEmail; ?>">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                  <!--button class="btn btn-primary submit-btn btn-sm" >Confirm</button-->
                </div>




                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="First Name" name="firstName">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Last Name" name="lastName">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="input-group">
                    <input type="password" class="form-control" placeholder="Password" name="password">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <input type="password" class="form-control" placeholder="Password Check" name="checkPassword">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="input-group">
                    <input type="tel" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                           class="form-control" placeholder="Phone Number" name="phoneNum">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="form-group d-flex justify-content-center">
                  <div class="form-check form-check-flat mt-0">
<!--

                    <label class="form-check-label">
                      <input type="checkbox" class="form-check-input" checked> I agree to the terms
                    </label>
-->
                  </div>
                </div>
                <div class="form-group">
                  <button class="btn btn-primary submit-btn btn-block">SIGN UP</button>
                </div>
                <div class="text-block text-center my-3">
                  <span class="text-small font-weight-semibold">Already have and account ?</span>

                  <a href="login" class="text-black text-small">SIGN IN</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../vendors/js/vendor.bundle.base.js"></script>
  <script src="../../vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="../../js/off-canvas.js"></script>
  <script src="../../js/hoverable-collapse.js"></script>
  <script src="../../js/misc.js"></script>
  <script src="../../js/settings.js"></script>
  <script src="../../js/todolist.js"></script>
  <!-- endinject -->
</body>

<script>
  function check() {
    if(RegisterForm.email.value == "") {
      alert("Email value does not exist");
      RegisterForm.email.focus();
      return false;
    }
    else if(RegisterForm.password.value == "") {
      alert("Password value does not exist");
      RegisterForm.password.focus();
      return false;
    }
    else if(RegisterForm.checkPassword.value == "") {
      alert("Password Check value does not exist");
      RegisterForm.checkPassword.focus();
      return false;
    }
    else if (RegisterForm.password.value != RegisterForm.checkPassword.value) {
      alert("Password and password check don't match");
      RegisterForm.password.focus();
      return false;
    }
    else return true;
  }
</script>

</html>
